/**
 * Shared `fast-check` arbitraries (generators) for property-based tests.
 *
 * Used across multiple property tests defined in `tasks.md` and `design.md`.
 * Each generator is documented with the property number it supports.
 *
 * Requirements: 6.1, 5.4, 13.8, 9.6
 */

import fc, { type Arbitrary } from "fast-check";

// ---------------------------------------------------------------------------
// Shared types & constants
// ---------------------------------------------------------------------------

/**
 * The 14 module ids referenced throughout the design (`design.md` §"ModuleId").
 * Re-exported so tests can constrain inputs to known modules.
 */
export const MODULE_IDS = [
  "than-so-hoc",
  "bat-tu",
  "xem-que",
  "cat-hung",
  "lich-van-nien",
  "tu-vi",
  "phong-thuy",
  "xem-ten",
  "lich-ca-nhan",
  "tu-dien",
  "hop-tuoi",
  "xem-ngay-tot",
  "sao-han",
  "ai-chat",
] as const;

export type ModuleId = (typeof MODULE_IDS)[number];

/**
 * Canonical breakpoints used by Property 8 (no-horizontal-overflow).
 * Mirror of `arbBreakpoint` shortlist from `design.md` §generators.
 */
export const STANDARD_BREAKPOINTS = [320, 768, 1024, 1440] as const;

/** Stable base timestamp used for time-related generators (~2023-11-14T22:13:20Z). */
const BASE_TIMESTAMP_MS = 1_700_000_000_000;

/** 30 days in milliseconds. */
const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;

/** Maximum Retry-After window in seconds (24h). */
const MAX_RETRY_AFTER_SECONDS = 86_400;

// ---------------------------------------------------------------------------
// arbForm — Property 11 (validation purity / live-revalidation)
// ---------------------------------------------------------------------------

/** Shape of a Form_Input value bag generated by {@link arbForm}. */
export interface ArbFormValue {
  /** Day-of-month input. Range covers invalid (>31, <1) and valid values. */
  day: number;
  /** Month input. Range covers invalid (>12, <1) and valid values. */
  month: number;
  /** Year input. Range covers <1900 and >2100 (out-of-range) plus valid range. */
  year: number;
  /** Hour input. Range covers <0 and >23 plus valid hours. */
  hour: number;
  /** Phone digits (digits-only string). Length range covers <10 and ≥10. */
  phoneDigits: string;
  /** Free-text name input. Arbitrary unicode. */
  name: string;
}

/** Digit characters used by {@link arbForm} to build phone strings. */
const DIGIT_CHARS = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"] as const;

/**
 * Generates a {@link ArbFormValue} for property tests on form validation.
 *
 * Used by Property 11 (validation purity) — see `design.md`.
 */
export const arbForm: Arbitrary<ArbFormValue> = fc.record({
  day: fc.integer({ min: -100, max: 200 }),
  month: fc.integer({ min: -10, max: 30 }),
  year: fc.integer({ min: 1500, max: 2200 }),
  hour: fc.integer({ min: -5, max: 30 }),
  phoneDigits: fc
    .array(fc.constantFrom(...DIGIT_CHARS), { minLength: 0, maxLength: 20 })
    .map((chars) => chars.join("")),
  name: fc.string(),
});

// ---------------------------------------------------------------------------
// arbConversation — Property 19 (persist AI conversation round-trip)
// ---------------------------------------------------------------------------

/** Shape of a single AI chat message generated by {@link arbConversation}. */
export interface ArbMessage {
  /** UUID-like identifier. */
  id: string;
  /** Author role of the message. */
  role: "user" | "assistant";
  /** Markdown-safe text. May contain unicode, newlines, emoji. */
  content: string;
  /** Unix milliseconds within the last 30 days from {@link BASE_TIMESTAMP_MS}. */
  timestamp: number;
}

/** Single message arbitrary used by {@link arbConversation}. */
const arbMessage: Arbitrary<ArbMessage> = fc.record({
  id: fc.uuid(),
  role: fc.constantFrom<ArbMessage["role"]>("user", "assistant"),
  content: fc.string({ unit: "grapheme" }),
  timestamp: fc
    .integer({ min: 0, max: THIRTY_DAYS_MS })
    .map((delta) => BASE_TIMESTAMP_MS - delta),
});

/**
 * Generates an array of AI chat messages (0–50 long).
 *
 * Used by Property 19 (persist hội thoại AI round-trip) — see `design.md`.
 */
export const arbConversation: Arbitrary<ArbMessage[]> = fc.array(arbMessage, {
  minLength: 0,
  maxLength: 50,
});

// ---------------------------------------------------------------------------
// arbReadingList — Profile property tests (saved readings)
// ---------------------------------------------------------------------------

/** Shape of a saved reading generated by {@link arbReadingList}. */
export interface ArbSavedReading {
  /** Unique reading id. */
  id: string;
  /** One of the 14 known {@link ModuleId} values. */
  module: ModuleId;
  /** Display title. */
  title: string;
  /** Unix milliseconds when the reading was saved. */
  savedAt: number;
  /** Optional note attached to the reading. */
  note: string | null;
}

/** Single saved-reading arbitrary used by {@link arbReadingList}. */
const arbSavedReading: Arbitrary<ArbSavedReading> = fc.record({
  id: fc.uuid(),
  module: fc.constantFrom<ModuleId>(...MODULE_IDS),
  title: fc.string({ minLength: 0, maxLength: 200 }),
  savedAt: fc
    .integer({ min: 0, max: THIRTY_DAYS_MS })
    .map((delta) => BASE_TIMESTAMP_MS - delta),
  note: fc.option(fc.string({ minLength: 0, maxLength: 500 }), { nil: null }),
});

/**
 * Generates a list of {@link ArbSavedReading} (0–100 long) for profile tests.
 *
 * Used by profile filter / sort / dedupe property tests.
 */
export const arbReadingList: Arbitrary<ArbSavedReading[]> = fc.array(
  arbSavedReading,
  { minLength: 0, maxLength: 100 },
);

// ---------------------------------------------------------------------------
// arbBreakpoint — Property 8 (no horizontal overflow)
// ---------------------------------------------------------------------------

/**
 * Generates a viewport width drawn from a wide set of real-world breakpoints.
 *
 * Used by Property 8 (no horizontal overflow) — see `design.md`.
 */
export const arbBreakpoint: Arbitrary<number> = fc.constantFrom(
  320,
  360,
  375,
  390,
  414,
  480,
  640,
  768,
  820,
  1024,
  1280,
  1366,
  1440,
  1536,
  1920,
);

// ---------------------------------------------------------------------------
// arbHttpStatus — Property 15 (ErrorState for 4xx/5xx)
// ---------------------------------------------------------------------------

/**
 * Generates an HTTP status code in the error range \[400, 599\].
 *
 * Used by Property 15 (ErrorState chuẩn cho mọi mã 4xx/5xx) — see `design.md`.
 */
export const arbHttpStatus: Arbitrary<number> = fc.integer({
  min: 400,
  max: 599,
});

/** Constant generator returning HTTP 429 — useful for rate-limit specific tests. */
export const arbHttpStatus429: Arbitrary<429> = fc.constant(429);

// ---------------------------------------------------------------------------
// arbRetryAfterHeader — Property 16 (parser Retry-After)
// ---------------------------------------------------------------------------

/** Shape returned by {@link arbRetryAfterHeader}. */
export interface ArbRetryAfter {
  /** Raw header value as it would arrive on the wire (or `null` if absent). */
  header: string | null;
  /** Parser's expected output in seconds; `0` for invalid / missing values. */
  expectedSeconds: number;
  /** Base timestamp (ms) used to build / interpret HTTP-date headers. */
  now: number;
}

/** Integer-seconds branch: a non-negative integer encoded as a base-10 string. */
const arbRetryAfterSeconds: Arbitrary<ArbRetryAfter> = fc
  .tuple(
    fc.integer({ min: 0, max: MAX_RETRY_AFTER_SECONDS }),
    fc.integer({ min: 0, max: 2_000_000_000_000 }),
  )
  .map(([seconds, now]) => ({
    header: String(seconds),
    expectedSeconds: seconds,
    now,
  }));

/** HTTP-date branch: `now + delta` formatted via `toUTCString`. */
const arbRetryAfterHttpDate: Arbitrary<ArbRetryAfter> = fc
  .tuple(
    fc.integer({ min: 0, max: MAX_RETRY_AFTER_SECONDS }),
    fc.integer({ min: 0, max: 2_000_000_000_000 }),
  )
  .map(([deltaSeconds, now]) => {
    const target = now + deltaSeconds * 1000;
    return {
      header: new Date(target).toUTCString(),
      // `toUTCString` truncates to whole seconds, so the round-trip is exact
      // when `now` is already on a second boundary; we floor to be safe.
      expectedSeconds: Math.max(
        0,
        Math.floor((new Date(target).getTime() - now) / 1000),
      ),
      now,
    };
  });

/** Garbage / unparseable string branch — parser must yield 0. */
const arbRetryAfterGarbage: Arbitrary<ArbRetryAfter> = fc
  .tuple(
    fc
      .string({ minLength: 1, maxLength: 30 })
      // Filter out anything that could legitimately parse as a non-negative
      // integer or a valid Date, so we keep this branch firmly invalid.
      .filter((s) => {
        const trimmed = s.trim();
        if (trimmed.length === 0) return false;
        if (/^\d+$/.test(trimmed)) return false;
        const parsed = Date.parse(trimmed);
        return Number.isNaN(parsed);
      }),
    fc.integer({ min: 0, max: 2_000_000_000_000 }),
  )
  .map(([garbage, now]) => ({
    header: garbage,
    expectedSeconds: 0,
    now,
  }));

/** Missing-header branch — `null` must yield 0. */
const arbRetryAfterNull: Arbitrary<ArbRetryAfter> = fc
  .integer({ min: 0, max: 2_000_000_000_000 })
  .map((now) => ({ header: null, expectedSeconds: 0, now }));

/**
 * Generates a Retry-After header fixture: integer seconds, HTTP-date, garbage,
 * or `null`. The `expectedSeconds` field is the parser's expected output.
 *
 * Used by Property 16 (parser Retry-After) — see `design.md`.
 */
export const arbRetryAfterHeader: Arbitrary<ArbRetryAfter> = fc.oneof(
  arbRetryAfterSeconds,
  arbRetryAfterHttpDate,
  arbRetryAfterGarbage,
  arbRetryAfterNull,
);

// ---------------------------------------------------------------------------
// arbMousePosition — Property 18 (tilt-card angle clamp)
// ---------------------------------------------------------------------------

/** Shape of a mouse position fixture generated by {@link arbMousePosition}. */
export interface ArbMousePosition {
  /** Cursor X within the card, in pixels: `[0, cardWidth]`. */
  x: number;
  /** Cursor Y within the card, in pixels: `[0, cardHeight]`. */
  y: number;
  /** Card width in pixels: `[100, 1200]`. */
  cardWidth: number;
  /** Card height in pixels: `[100, 1200]`. */
  cardHeight: number;
}

/**
 * Generates mouse positions inside a card's bounds.
 *
 * Card dimensions are picked first, then `x`/`y` are constrained to the
 * resulting rectangle. Used by Property 18 (tilt-card giới hạn độ nghiêng) —
 * see `design.md`.
 */
export const arbMousePosition: Arbitrary<ArbMousePosition> = fc
  .record({
    cardWidth: fc.integer({ min: 100, max: 1200 }),
    cardHeight: fc.integer({ min: 100, max: 1200 }),
  })
  .chain(({ cardWidth, cardHeight }) =>
    fc.record({
      cardWidth: fc.constant(cardWidth),
      cardHeight: fc.constant(cardHeight),
      x: fc.integer({ min: 0, max: cardWidth }),
      y: fc.integer({ min: 0, max: cardHeight }),
    }),
  );
